### ISSUE TITLE
longer maximum profile name

### ISSUE THREAD

**Issue by Memblers** [Myself086/Project-Nested#1]
The maximum name for profile creation is 32 chars.  But NES ROMs sorted by an ID/renaming utility will often include the full subtitle and tags, such as "Ninja Gaiden II - The Dark Sword of Chaos (U) [!].nes",  "Skate or Die 2 - The Search for Double Trouble (U) [!].nes", and these filenames are too long.

Not super important, but it would be more convenient.

**Comment by Myself086** [comment]
128 characters instead of 32 in v1.4.
