### ISSUE TITLE
Is iNES header 2.0 supported?

### ISSUE THREAD

**Issue by CaptainHIT** [Myself086/Project-Nested#11]
Looks like iNES 2.0 header isn't supported. Just tried a rom with an iNES 2.0 header and the exe gave me a warning that mapper 17 isn't supported. Tried the same game rom (and same region and revision) with a iNES 1 header and it works. It's a game that is marked as compatible in the list.

**Comment by Myself086** [comment]
iNES 2.0 isn't supported yet.

Some games have been reported as having mapper 14 or 17 instead of what's listed on the spreadsheet, these ROMs were modified to fit on a copying device and are harder to emulate on SNES than their originals. Mappers 14 and 17 are also blacklisted.

**Comment by CaptainHIT** [comment]
I mean it was a clean (unmodified) game. It doesn't have mapper 17, it's just the exe giving me this error if iNES 2.0 is applied instead of iNES header 1.

**Comment by Myself086** [comment]
There was a bug with how the mapper was read, fixed in v1.4.
