### ISSUE TITLE
Pinball USA has unplayable

### ISSUE THREAD

**Issue by michele559** [Myself086/Project-Nested#15]
This game resets to the title screen during normal gameplay and that changes "★✰✰✰✰" to Unplayable Spreadsheet. Could even anymore tried it FCEUX on my PC??

**Comment by Myself086** [comment]
Pinball falls in the following category:
<html><body>
<google-sheets-html-origin>

★★✰✰✰ | Orange, intro only or crash during early gameplay
-- | --



</body>
</html>

Please stop spamming me about Pinball.

If you get it to work on the latest version of Project Nested, please provide instructions.

**Comment by michele559** [comment]
Changes the

> Pinball changes in the following category:
> 
> ★✰✰✰✰	Red, not playable
> Please stop spamming me about Pinball.
> 
> If you get it to work on the latest version of Project Nested, please provide instructions.

**Comment by michele559** [comment]
Pinball changes in the following category:
### 

> Pinball falls in the following category:
> 
> ★★✰✰✰	Orange, intro only or crash during early gameplay
> Please stop spamming me about Pinball.
> 
> If you get it to work on the latest version of Project Nested, please provide instructions.

Changes the "★✰✰✰✰ | Red, not playable" to be unplayable due to very slow/laggy/glitched tiles or gets in early or normal gameplay and boots well but crash or lockups at same early point to be unstable.

**Comment by michele559** [comment]
> Pinball falls in the following category:
> 
> ★★✰✰✰	Orange, intro only or crash during early gameplay
> Please stop spamming me about Pinball.
> 
> If you get it to work on the latest version of Project Nested, please provide instructions.

Changes to the:

★★✰✰✰	Red, not playable

**Comment by michele559** [comment]
> Pinball falls in the following category:
> 
> ★★✰✰✰	Orange, intro only or crash during early gameplay
> Please stop spamming me about Pinball.
> 
> If you get it to work on the latest version of Project Nested, please provide instructions.

Changes to the:

★✰✰✰✰	Red, not playable

**Comment by michele559** [comment]
category changes;
★✰✰✰✰ Red, not playable

**Comment by michele559** [comment]
> > Pinball falls in the following category:
> > ★★✰✰✰	Orange, intro only or crash during early gameplay
> > Please stop spamming me about Pinball.
> > If you get it to work on the latest version of Project Nested, please provide instructions.
> 
> Changes to the:
> 
> ★✰✰✰✰ Red, not playable



> Pinball falls in the following category:
> 
> ★★✰✰✰	Orange, intro only or crash during early gameplay
> Please stop spamming me about Pinball.
> 
> If you get it to work on the latest version of Project Nested, please provide instructions.

Pinball changes following category:

|---|---|
|★✰✰✰✰|Red, not playable|

**Comment by michele559** [comment]
> Pinball falls in the following category:
> 
> ★★✰✰✰	Orange, intro only or crash during early gameplay
> Please stop spamming me about Pinball.
> 
> If you get it to work on the latest version of Project Nested, please provide instructions.

Pinball changes following category:

|★✰✰✰✰|Red, not playable|
|---|---|

If you change the status bar on your spreadsheet?

**Comment by michele559** [comment]
> Pinball falls in the following category:
> 
> ★★✰✰✰	Orange, intro only or crash during early gameplay
> Please stop spamming me about Pinball.
> 
> If you get it to work on the latest version of Project Nested, please provide instructions.

Pinball changes following category:

|★✰✰✰✰|Red, not playable|
|---|---|

If you change the status bar on your spreadsheet?

**Comment by michele559** [comment]
> Pinball falls in the following category:
> 
> ★★✰✰✰	Orange, intro only or crash during early gameplay
> Please stop spamming me about Pinball.
> 
> If you get it to work on the latest version of Project Nested, please provide instructions.


Myself806's trying to Change the pinball category following:

|★✰✰✰✰|Red, not playable|
|---|---|
