### ISSUE TITLE
Pinball has problematic major resetting

### ISSUE THREAD

**Issue by qamichele59** [Myself086/Project-Nested#19]
The game reboots after you start the first level and you can hear the sound playing. Immediately Game works better when tried it on FCEUX on my Computer?

Pinball changes following category (red)

|★✰✰✰✰|Red, nothing happens or immediate crash|
|---|---|

If you fixed for v1.4 through but not working on previous versions will make it sad now :-(

**Comment by qamichele5959** [comment]
Changes category from red

**Comment by qamichele59** [comment]
This is a regression. Blocked or killed method

Il Sab 14 Ago 2021, 03:16 qamichele5959 ***@***.***> ha
scritto:

**Comment by qamichele59** [comment]
Pinball falls editing compatibility rating category
★✰✰✰✰
Red, nothing happens or immediate crash

If you fixed for v1.4 version instead after will you make it sad now :-(

Il Sab 14 Ago 2021, 19:37 Myself086 ***@***.***> ha scritto:

**Comment by qamichele59** [comment]
Edits compatibility category ``★★✰✰✰ Orange, Intro only or crash during
early/bad gameplay and the game has very slow/laggy/glitched up tiles or
gets in gameplay and boots or plays well but crashes or lockups at same
early point to be the unplayable and have major problems and/or are
consistent lockups``

Il Sab 14 Ago 2021, 19:37 Myself086 ***@***.***> ha scritto:
