### ISSUE TITLE
failures seen after loading SRM file

### ISSUE THREAD

**Issue by Memblers** [Myself086/Project-Nested#2]
The process of running the game, loading SRM feedback, and regenerating the ROM has caused some problems to appear in a couple games so far.

Dragon Quest 2 - Start new game, name entry screen looks OK.  After loading SRM, name entry screen is corrupted.
Little League Baseball - Game is playable.  After loading SRM, game only shows a black screen.

Both these games crash during gameplay, but I've avoided using an SRM file from a crashed session (in case corruption is possible somehow).  I've also made sure to delete the profiles, exit and restart the exe, and the problem was still reproduced.  Tested with v1.0.2 exe

**Comment by Myself086** [comment]
Was fixed with v1.3, reopen if this happens again.
