### ISSUE TITLE
Megaman Crash when playing with disable nmi auto detect

### ISSUE THREAD

**Issue by qamichele5959** [Myself086/Project-Nested#20]
I got this while trying to play this stage. Still crashes with interpreter exception. NMI mode worked when i tried it work on FCEUX on my Computer.

Megaman Changes following category:

|★★✰✰✰|Orange, intro only or crash during early gameplay|
|---|---|

It has fixed for the v1.4 through after make it sad now :-(.

**Comment by qamichele5959** [comment]
Now regression changes the category:

|★★✰✰✰|Orange, intro only or crash during early gameplay|
|---|---|

**Comment by Myself086** [comment]
Which stage?

**Comment by qamichele5959** [comment]
> Which stage?

Now are regressiong edits following category

|★★✰✰✰|Orange, intro only or crash during early gameplay|
|--|--|

Fixed for v1.4 but will make it sad now :(......

**Comment by Myself086** [comment]
You failed to answer my question.
