### ISSUE TITLE
Is custom palette support possible?

### ISSUE THREAD

**Issue by ZReport** [Myself086/Project-Nested#28]
Was wondering if support for palettes is possible to be bundled into each compile?  Might be interesting if possible!

**Comment by Myself086** [comment]
It is possible, It was requested months ago but I didn't get to it due to low priority.

**Comment by ZReport** [comment]
Oh cool!  Take your time on it then!  Not even important compared to other issues. 😀

**Comment by Myself086** [comment]
Added in v1.5
