### ISSUE TITLE
super mario 3 just crashes at level 7 from world 5 

### ISSUE THREAD

**Issue by johneymute** [Myself086/Project-Nested#38]
despite i had added 8KB of srm ram to that game,it still crashes but this time at level 7 from world 5 once i enter the pipe to the bonus area or the pipe at the end,the bsod says that it executed an unsupporten iligal opcode.

![IMG_E1446](https://user-images.githubusercontent.com/90924608/136587250-3501b4ac-2966-4bc6-b30c-7fae73eeee66.JPG)

what do you think does it really has something to do with the iligal opcodes??

besides i activated iligal opcodes in the settings but it still just did not solve the problem, that’s absurd.

**Comment by Myself086** [comment]
I can't believe I missed this, fixed via patch available on the spreadsheet.
