### ISSUE TITLE
No video output but sound works fine

### ISSUE THREAD

**Issue by soniccd123** [Myself086/Project-Nested#4]
Hello, first of all, amazing project!!!

I've tried to test Super Mario Bros in a real SNES (SNS-CPU-RGB-01) using a flashcard and, while the game actually has sound output just as one would expect, theres absolutely no video output, just a black screen.

Thanks,

Soniccd123

PS: I've made some tests after reading the NESdev post about the emulator sugesting that this behavior is reproducible in HIGAN and that could be some PPU initialization problem. To test it, i've used a normal SNES cart to initialize the PPU, removed this cart with the console running, inserted my flashcard and pressed reset on the console. With this the screen came to life, i hope this helps to find a fix.

**Comment by Myself086** [comment]
I implemented your change to v1.1
