### ISSUE TITLE
i want my nes games in true RGB colors on snes

### ISSUE THREAD

**Issue by johneymute** [Myself086/Project-Nested#46]
hi, i know you mentioned a long time ago early on that the colors fr om nes games on nested are already RGB,however to me they look more like authentic composite video colors from the nes,but for what i do know is that the famicom tv outputs true RGB colors,so i was thinking ,what if you could implement an option on nested to choose between   mode 2 wich generates pseudo composite colors(YUV) or mode 4 wich generates direct RGB colors,that would be great sothat people could choose for YUV for a more authentic look or they could choose for RGB for a much more modern look,you have to see what i mean to believe it ,UNLESS you did already a research on this and discovered that the RGB colorpallet from the snes is limited and that they don't cover all colors from the nes colorspallet to replace them.

![IMG_E2001](https://user-images.githubusercontent.com/90924608/155850712-93d91273-089e-42fc-9ac9-6fdbd14e880b.JPG)

see the clear differences between composite video colors and RGB colors and judge for yourself.

**Comment by symbios24** [comment]
I think this depends from what cable you have on your snes eg: to rca cable or scart true rgb cable

**Comment by johneymute** [comment]
> I think this depends from what cable you have on your snes eg: rca composite cable or scart true rgb cable

Well i do use rgb cables for my snes but i tell you that despites the signal is cleaner then composite video,BUT the colors from nes games on it trough nested ,just don’t look that bright,am sure it has nothing to do with the wrong scart cable or input because otherwise it would only show composite video, note that i used a moddified thirth party NGC cable to get rgb out of my snes and i do saw a difference between composite and RGB so it does work,now before you would say that nes games and the nes ppu were not designed for RGB,please note that the ppu from both the famicom tv and famicom titler do generate an RGB colorpallet,and for what i do know is that mode 2 on snes does not use RGB colorpallet,it’s more like a YUV colorpallet wich originates from component,but mode 4 from the snes does use a direct RGB colorpallet for true RGB colors,
Yes am surprised too because back then i tout all colors from the snes colorpallet were true RGB and so i tout that whether background mode you use,the colorpallet is RGB,but no,sadly not all colors are RGB and you cannot use RGB colors in every background mode,nested uses mode 2 for nes games for a authentic look,but just imagine if nested would use mode 4,then nes games could just look as bright and vibrant as on the famicom tv or famicom titler.

**Comment by Myself086** [comment]
SNES can only use RGB555. I don't know what mode 2 and mode 4 you're talking about.
Project Nested v1.5 will have an option to customize the NES palette.

**Comment by johneymute** [comment]
> SNES can only use RGB555. I don't know what mode 2 and mode 4 you're talking about.
> Project Nested v1.5 will have an option to customize the NES palette.


Well uhm if am not mistaken for what i,ve readed is that mode 2 does mot use direct RGB color while mode 4 does use RGB color,but i wonder what’s RGB555 ??? Is it the limited amount of colorpallet the snes uses? Does it mean that not all 32768 colors are RGB or something??

also can you already give use a glimps about the extra features of nested 1,5 aside from costum colorpallet??

do you know when it will be released??

thanks alot😁

**Comment by Myself086** [comment]
You are probably referring to "direct-color" of modes 3, 4 and 7 which doesn't use the 256 color palettes but are still limited by RGB555 and even more limited than using color palettes because it's almost like using RGB332.
RGB555 means 5 bits for red, green and blue. It's a total of 32768 colors. For more detail about it, you can google "RGB555 ".

In my experience, saying "if am not mistaken" is an indication that you are wrong and possibly ignoring that you are wrong. If you happen to say it for other topics, start questioning the answers that you know and redo some research.

I don't have an exact time for release. I just know what I want to add and sometimes I cut it short if it's too close to a time that I need a break.

To see what's already added in the upcoming release, check the CHANGELOG.txt file here:
https://github.com/Myself086/Project-Nested/blob/master/CHANGELOG.txt

**Comment by johneymute** [comment]
Thanks for mention this ,i got 2 questions left,
1 will the spade card game,memory game of brk bug in mario 3 be fixed?
2.will dpcm sound finally be supported with the upcoming nested v1.5???

thanks alot and take your time all the way.

**Comment by Myself086** [comment]
1, There's a patch for smb3 mini-games in the "Patch" column of the spreadsheet so they won't crash anymore but spade game has scrolling issues.
2, Not for v1.5 but I have plans for it.

**Comment by Myself086** [comment]
Added in v1.5
