### ISSUE TITLE
Can’t wait till mapper 90 and mapper 211 will be supported

### ISSUE THREAD

**Issue by johneymute** [Myself086/Project-Nested#57]
I really really hope those 2 mappers will be supported sothat we can play the nes versions of supermarioworld and donkeykong country on snes,why? Because no matter how unofficial the bad they are,but once they will run on snes,we are full circle,just imagine a snes game ported to the nes and getting back on the snes at were it came from but then trough nested,that would be a wet dream come true,in fact it’s already in my book a wet dream that those 2 mentioned games did unofficially came out on the nes wich once i heard about it did hit me like an atom bomb,
For 1 thing,theres an unofficial nes version of tetris attack wich was ported from the snes version,but somebody on youtube managed to get it run on nested wich waa really cool to see because of going full circle😁
Also tetris from tengen also does run on nested albeit somewhat buggy & glitchy at times but it’s playible so it might be fair to see donkeykong country 4 and supermarioworld also running on nested,also since i didn’t found mmc3 hacks of it,not yet,so let’s hope that both of my wishes come true.

**Comment by Myself086** [comment]
211 is high priority but I don't think I've heard requests for 19 until now.

Speaking of Tetris Attack, check out Panel Attack which is a near perfect clone for PC with online play and leaderboard. I was one of the devs around the time I started Project Nested.

As for Super Mario World NES, I made an editor for the game in 2017. I'm not sure where it's distributed.

Now that's going full circle on my timeline. 😄

**Comment by johneymute** [comment]
Hi, am sorry i was ment to say mapper 90 but due a typo from me i typed in mapper 19, but i have corrected that,
So be this i am 100% sure that it should be mapper 90, i hope you will have demand for that mapper too,
About panel attack,i didn’t knew you were involved in that as well, that’s pretty interesting😁
