### ISSUE TITLE
 future SA1 support for nested ??

### ISSUE THREAD

**Issue by johneymute** [Myself086/Project-Nested#61]
A cool option wich i would consider a welcome edition JUST IN CASE if some nes games will never ever run at full speed and if there will be always lots of unavoidible slowdown in those nes games like when there’re lots of enemy’s on screen like in kirby’s adventure etc,,, (even after those multiple sram upgrades) then an option to use the SA1 chip as the master cpu can be handy to speed things up alot to avoid such slowdown,BUT if you are convinced that the SA1 chip is just inrelevant and that the slow snes cpu chip could run even the most processive demanding nes game at full speed in the near future,then i would suggest to not bother with the SA1 chip as an option,😁

**Comment by Myself086** [comment]
Using SA1 is possible but I would need to rewrite every I/O emulation.
But SA1 is not part of my initial goal for this project and I won't do it without a decent pay for my time.

**Comment by johneymute** [comment]
Snes cpu just powerful enougj
