### ISSUE TITLE
 am so excited to see mmc5 to mmc3 hacked nes games to partially or fully run on nested.

### ISSUE THREAD

**Issue by TumaTSB1982** [Myself086/Project-Nested#69]
Not an real issue but Since i recently know that the nested oroject has been ended as of 1.7,(unless i,somebody else here or we both in the community could pay you together $300.000 to continue on the development of it to it’s most possible peak capabilities)we no longer could expect to get support for mmc5 games anymore,but since there’re many nes games being ported by hackers from unofficial mappers or the mmc5 chip to the mmc3 chip,games such as splatter house,prisoners of war and castlevania 3 etc,, are certainly prime examples of this and so we can only hope for more😁

**Comment by TumaTSB1982** [comment]
![130DB647-1D27-4F0E-BB3F-D1A4F20FC55C](https://user-images.githubusercontent.com/126181679/220975062-8a520be1-f3f5-4c30-a2d0-ffa1a4059c7b.jpeg)

**Comment by Myself086** [comment]
Go beg for $300,000 elsewhere.
