### ISSUE TITLE
Error reporting

### ISSUE THREAD

**Issue by LeeHellewell** [Myself086/Project-Nested#7]
I got this one on Mega Man 2 using an Everdrive on a PAL SNES. It won't load past the opening screen to start the game. I used v1.1 

![20201015_220745](https://user-images.githubusercontent.com/72950118/96193856-0b314000-0f41-11eb-86d2-0cafbe18d82f.jpg)

On another note, this is emulator is amazing! Having a backwards compatible SNES was the stuff of dreams in the early 90s 🙂 I enjoyed playing Mario 1 last night

**Comment by Myself086** [comment]
The compatibility list says "disable NMI auto detect" and is playable but not fully tested. I haven't tested the game myself. Let me know if you're able to beat the game.

Here's a link for the compatibility spreadsheet:
https://docs.google.com/spreadsheets/d/1xKZIyNz1DSI3ZBdMfaTEaa_9b6IEABx-ZPwOb6XqcLQ/edit?usp=sharing

**Comment by LeeHellewell** [comment]
Thanks very much. It's working now 🙂 I'll try and complete it so that can be marked off the list. Speaking of which, where do you want people to let you know about completed games?

**Comment by LeeHellewell** [comment]
I didn't check the settings required on the compatibility list Project Nested. The problem was the user (me!), not the program
