### ISSUE TITLE
super mario bros 3 not working

### ISSUE THREAD

**Issue by 1392-github** [Myself086/Project-Nested#72]
When I try to convert Super Mario Bros. 3, it says Mapper 5 is not supported
please add mapper 5 support

**Comment by BigGaySquirrel** [comment]
I should state i am not an administrator for this or developer for the project but

1. This rom has already been converted with a graphical face lift as part of the super mario all stars release which combines all the original nes games.
2. Have you checked the project NESTED matrix to see if the rom is compatible and/or supported. Optimum settings will be listed there but i have personally found games do not run as they were originally intended to on og NES hardware.

If this isn't the answer you were looking for you'll have to wait for a developer or admin to chime in I'm afraid.

**Comment by Myself086** [comment]
Super Mario Bros. 3 uses mapper 4, you have an incorrect ROM. The game runs near flawlessly if you follow the settings on the spreadsheet. The only incompatibility is the spade game.

**Comment by BigGaySquirrel** [comment]
> Super Mario Bros. 3 uses mapper 4, you have an incorrect ROM. The game runs near flawlessly if you follow the settings on the spreadsheet. The only incompatibility is the spade game.

I'm glad you get perfect results but i have found metroid, zelda 1 and kirby have all run very poorly and crashed at various points during my time playing them.
Don't get me wrong, I'm grateful NESTED exists as i Don't own a nes anymore and other than emulation have no way of playing those games.

Going back to the original point though, why don't you just play mario all stars?
Makes no sense to convert the rom, let alone complain about incompatibility when a superior version exists that was developed by the big "N" themselves.
