### ISSUE TITLE
SRAM is missing

### ISSUE THREAD

**Issue by 1392-github** [Myself086/Project-Nested#73]
Using bsnes-plus emulator gives SRAM is missing error
![miss](https://github.com/Myself086/Project-Nested/assets/110650515/7fbc6f7b-ccf7-495a-a938-78c38f494e35)

**Comment by Myself086** [comment]
Download the newest version of BSNES-plus or reduce SRAM to 128KB, a blue setting on Project_Nested.exe, set to 7 or mouse over for details. This version of BSNES-plus treats 256KB as 0KB.

This issue exists in different forms on various emulators and flash card devices. The solution may vary based on the emulator or flash card device.
